### ISSUE TITLE
`pipx run cookieplone` does not update Cookieplone to latest version

### ISSUE THREAD

**Issue by stevepiercy** [plone/cookieplone#53]
Try the following.

```shell
pipx install cookieplone==0.8.0   
  installed package cookieplone 0.8.0, installed using Python 3.12.2
  These apps are now globally available
    - cookieplone
done! ✨ 🌟 ✨
```

```shell
$ cookieplone --version          
Cookieplone 0.8.0 from /Users/stevepiercy/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookieplone (Cookiecutter 2.6.0, Python 3.12.2 (main, Apr 18 2024, 11:19:24) [Clang 15.0.0 (clang-1500.1.0.2.5)])

Made with ❤️ by the Plone Community
```

```shell
pipx run cookieplone 
⚠️  cookieplone is already on your PATH and installed at /Users/stevepiercy/.local/bin/cookieplone. Downloading and running anyway.
...
ctrl-c
```

This statement is misleading, as it implies that Cookieplone is "Downloading". It does not do that, as shown in the next step.

```shell
$ cookieplone --version          
Cookieplone 0.8.0 from /Users/stevepiercy/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookieplone (Cookiecutter 2.6.0, Python 3.12.2 (main, Apr 18 2024, 11:19:24) [Clang 15.0.0 (clang-1500.1.0.2.5)])

Made with ❤️ by the Plone Community
```

Here are some options to consider.

1. Force Cookieplone to update to the latest version with `pipx run cookieplone`.
2. Create a new optional flag of `--use-installed` that will use the currently installed version of Cookieplone if found, else install the latest version.
3. Document how to upgrade Cookieplone to the latest version or install a specific version.

   ```shell
   # Installs the latest version of cookieplone if it has not yet been installed
   pipx install cookieplone
   # Upgrades an existing installation of cookieplone
   pipx upgrade cookieplone
   # Installs a specific version of cookieplone
   pipx install cookieplone==0.8.1
   ```

I reckon we need to do Option 3 before the start of PloneConf trainings on Monday, as this will trip up many users.

See also https://github.com/plone/documentation/issues/1781#issuecomment-2485179938.

Pinging trainers so they know what to expect. @polyester @tkimnguyen @ericof @nileshgulia1 @danalvrz @sneridagh @iRohitSingh. Also @davisagli and @erral who are actively contributing here.

**Comment by davisagli** [comment]
@stevepiercy It works fine for me if I use `pipx run cookieplone` (which creates a temporary virtualenv) instead of just `cookieplone` (which runs cookieplone that was previously installed):

```
(:|✔) % pipx install cookieplone==0.8.0                                                                                 ~
  installed package cookieplone 0.8.0, installed using Python 3.12.2
  These apps are now globally available
    - cookieplone
done! ✨ 🌟 ✨

(:|✔) % pipx run cookieplone --version                                                                                  ~
⚠️  cookieplone is already on your PATH and installed at /Users/davisagli/.local/bin/cookieplone. Downloading and
    running anyway.
Cookieplone 0.8.1 from /Users/davisagli/.local/pipx/.cache/f1ba297edd926c7/lib/python3.12/site-packages/cookieplone 
(Cookiecutter 2.6.0, Python 3.12.2 (main, Aug 25 2024, 21:19:07) [Clang 14.0.3 (clang-1403.0.22.14.1)])

Made with ❤️ by the Plone Community
```

`pipx run cookieplone` is what we already have documented in https://6.docs.plone.org/install/create-project-cookieplone.html ... is there somewhere else where we said to just run `cookieplone`? If so we should change that.

**Comment by stevepiercy** [comment]
@davisagli OK, so my results are a false alarm. I wasn't sure whether pipx used the already installed version of cookieplone or created a temporary virtual environment. The `--version` flag clarifies that it uses a temporary one. Closing this issue and the other linked to this issue.
